### ISSUE TITLE
I get the error "server.createRoom() ERROR InvalidStateError: Channel closed"

### ISSUE THREAD

**Issue by WangYuLue** [mganeko/mediasoup_sample#6]
hello,i want your help:

I run the command `npm start` on my laptop ,it work well!

but when I run on the remote server , it's have some Error:

here is the log
```
Web server start. http://localhost:3000/
server.createRoom() ERROR InvalidStateError: Channel closed
    at Object.close (/root/Projects/webrtcTest/mediasoup_sample/node_modules/mediasoup/lib/Channel.js:246:14)
    at Channel.close (/root/Projects/webrtcTest/mediasoup_sample/node_modules/mediasoup/lib/Channel.js:169:9)
    at Worker.close (/root/Projects/webrtcTest/mediasoup_sample/node_modules/mediasoup/lib/Worker.js:134:17)
    at ChildProcess.Worker._child.on (/root/Projects/webrtcTest/mediasoup_sample/node_modules/mediasoup/lib/Worker.js:103:9)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by mganeko** [comment]
Thanks for your interest.
Sorry, I do not know what is happening in your server.

**Comment by diggymo** [comment]
same issue for me.

**Comment by mganeko** [comment]
I am afraid that you are using mediasoup V2.
Please try another example by footniko.
 
https://github.com/footniko/mediasoup-sample

**Comment by mganeko** [comment]
For mediasoup v2, please try https://github.com/mganeko/mediasoup_sample_v2
